version: 2
jobs:
  build:
    docker:
      - image: beevelop/ionic:latest
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Building android
          command: ionic cordova build android -Y
      - run:
          name: Ought to Copy
          command: cp -r platforms/android/build/outputs/apk $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: platforms/android/build/outputs/apk/android-debug.apk
