version: 2
jobs:
  build:
    docker:
      - image: beevelop/ionic:latest
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Building android
          command: |
            ionic cordova build android -Y
            find . -type f -iname "*.apk"
      - store_artifacts:
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
