version: 2
jobs:
  build:
    docker:
      - image: beevelop/ionic:latest
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Building android
          command: |
            find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
            mkdir -p /tmp/build
            ionic cordova build android -Y
            cp platforms/android/build/outputs/apk/ /tmp/build
      - store_artifacts:
          path: /tmp/build
