version: 2
jobs:
  build:
    docker:
      - image: beevelop/ionic:latest
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Building android
          command: |
            ionic cordova build android -Y
            mv ./platforms/android/app/build/outputs/apk/debug/app-debug.apk "./platforms/android/app/build/outputs/apk/debug/18 Avril.apk"
      - store_artifacts:
          path: "./platforms/android/app/build/outputs/apk/debug/18 Avril.apk"
